[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://trainmenow-api.onrender.com/api/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
